import { useThemeContext } from '@/context/ThemeContext'
import { Box, Button, Flex } from '@kuma-ui/core'
import Head from 'next/head'
import Header from './Header'
import Footer from './Footer'
import Grid from '@/components/Grid'
import Tournaments from './Tournaments'

export default function Home() {
  const { setIsDark } = useThemeContext()  


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Box as='main'>
        <Box>
          <Header/>
        </Box>
        <Button onClick={() => setIsDark((v) => !v)}>Toggle theme</Button>
        <Tournaments />

          <Grid />
      </Box>
      <Footer /> 
    </>
  )
}
